export const ErrorCodes = {
  // Autenticación y Cuentas
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  // Balotario y Preguntas
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  INVALID_ANSWER_OPTION: 'INVALID_ANSWER_OPTION',
  DATASET_UNAVAILABLE: 'DATASET_UNAVAILABLE',

  // Simulacro Oficial
  EXAM_SESSION_NOT_FOUND: 'EXAM_SESSION_NOT_FOUND',
  EXAM_ALREADY_SUBMITTED: 'EXAM_ALREADY_SUBMITTED',
  EXAM_TIME_EXPIRED: 'EXAM_TIME_EXPIRED',
  EXAM_INCOMPLETE_SUBMISSION: 'EXAM_INCOMPLETE_SUBMISSION',

  // Telemetría, Racha y Metas
  STREAK_CALCULATION_FAILED: 'STREAK_CALCULATION_FAILED',
  GOAL_SYNC_FAILED: 'GOAL_SYNC_FAILED',
  USER_PROGRESS_NOT_FOUND: 'USER_PROGRESS_NOT_FOUND',

  // Banco de Errores
  ERROR_ENTRY_NOT_FOUND: 'ERROR_ENTRY_NOT_FOUND',

  // Errores Genéricos y de Sistema
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
