import json
import re

replacements = [
    (r'Est\b', 'Está'),
    (r'est\b', 'está'),
    (r'estn\b', 'están'),
    (r'Estn\b', 'Están'),
    (r'va\b', 'vía'),
    (r'Va\b', 'Vía'),
    (r'vas\b', 'vías'),
    (r'Vas\b', 'Vías'),
    (r'seal\b', 'señal'),
    (r'Seal\b', 'Señal'),
    (r'seales\b', 'señales'),
    (r'Seales\b', 'Señales'),
    (r'sealizacin\b', 'señalización'),
    (r'Sealizacin\b', 'Señalización'),
    (r'sealética\b', 'señalética'),
    (r'Sealética\b', 'Señalética'),
    (r'sealizar\b', 'señalizar'),
    (r'sealados\b', 'señalados'),
    (r'seale\b', 'señale'),
    (r'seales\b', 'señales'),
    (r'grfico\b', 'gráfico'),
    (r'Grfico\b', 'Gráfico'),
    (r'grficos\b', 'gráficos'),
    (r'vehculo\b', 'vehículo'),
    (r'Vehculo\b', 'Vehículo'),
    (r'vehculos\b', 'vehículos'),
    (r'Vehculos\b', 'Vehículos'),
    (r'Trnsito\b', 'Tránsito'),
    (r'trnsito\b', 'tránsito'),
    (r'infraccin\b', 'infracción'),
    (r'Infraccin\b', 'Infracción'),
    (r'infracciones\b', 'infracciones'),
    (r'Infracciones\b', 'Infracciones'),
    (r'sanccin\b', 'sanción'),
    (r'sancin\b', 'sanción'),
    (r'sancionado\b', 'sancionado'),
    (r'sancionada\b', 'sancionada'),
    (r'evaluacin\b', 'evaluación'),
    (r'Evaluacin\b', 'Evaluación'),
    (r'categora\b', 'categoría'),
    (r'Categora\b', 'Categoría'),
    (r'Qu\b', '¿Qué'),
    (r'qu\b', '¿qué'),
    (r'Cundo\b', '¿Cuándo'),
    (r'cundo\b', '¿cuándo'),
    (r'Cul\b', '¿Cuál'),
    (r'cul\b', '¿cuál'),
    (r'Se\b', '¿Se'),
    (r'Si\b', '¿Si'),
    (r'si\b', '¿si'),
    (r'Influye\b', '¿Influye'),
    (r'La\b', '¿La'),
    (r'la\b', '¿la'),
    (r'las\b', '¿las'),
    (r'el\b', '¿el'),
    (r'El\b', '¿El'),
    (r'En\b', '¿En'),
    (r'Puede\b', '¿Puede'),
    (r'Constituye\b', '¿Constituye'),
    (r'Est\b', '¿Está'),
    (r'est\b', '¿está'),
    (r'ms\b', 'más'),
    (r'Ms\b', 'Más'),
    (r'mxima\b', 'máxima'),
    (r'mximas\b', 'máximas'),
    (r'mximo\b', 'máximo'),
    (r'mximos\b', 'máximos'),
    (r'mnima\b', 'mínima'),
    (r'mnimas\b', 'mínimas'),
    (r'mnimo\b', 'mínimo'),
    (r'mnimos\b', 'mínimos'),
    (r'podrn\b', 'podrán'),
    (r'podr\b', 'podrá'),
    (r'detencin\b', 'detención'),
    (r'Detencin\b', 'Detención'),
    (r'prevencin\b', 'prevención'),
    (r'Prevencin\b', 'Prevención'),
    (r'disminucin\b', 'disminución'),
    (r'Disminucin\b', 'Disminución'),
    (r'circulacin\b', 'circulación'),
    (r'Circulacin\b', 'Circulación'),
    (r'direccin\b', 'dirección'),
    (r'posicin\b', 'posición'),
    (r'Posicin\b', 'Posición'),
    (r'peatn\b', 'peatón'),
    (r'Peatn\b', 'Peatón'),
    (r'reglamentacin\b', 'reglamentación'),
    (r'obligacin\b', 'obligación'),
    (r'Obligacin\b', 'Obligación'),
    (r'autorizacin\b', 'autorización'),
    (r'revalidacin\b', 'revalidación'),
    (r'recategorizacin\b', 'recategorización'),
    (r'restriccin\b', 'restricción'),
    (r'interseccin\b', 'intersección'),
    (r'Interseccin\b', 'Intersección'),
    (r'intersecciones\b', 'intersecciones'),
    (r'situacin\b', 'situación'),
    (r'condicin\b', 'condición'),
    (r'conduccin\b', 'conducción'),
    (r'Conduccin\b', 'Conducción'),
    (r'atencin\b', 'atención'),
    (r'comisin\b', 'comisión'),
    (r'inspeccin\b', 'inspección'),
    (r'Inspeccin\b', 'Inspección'),
    (r'tambin\b', 'también'),
    (r'despus\b', 'después'),
    (r'Despus\b', 'Después'),
    (r'ser\b', 'será'),
    (r'deber\b', 'deberá'),
    (r'Deber\b', 'Deberá'),
    (r'debern\b', 'deberán'),
    (r'Debern\b', 'Deberán'),
    (r'habr\b', 'habrá'),
    (r'efecta\b', 'efectúa'),
    (r'lnea\b', 'línea'),
    (r'Lnea\b', 'Línea'),
    (r'lneas\b', 'líneas'),
    (r'lmite\b', 'límite'),
    (r'Lmite\b', 'Límite'),
    (r'lmites\b', 'límites'),
    (r'frreas\b', 'férreas'),
    (r'frrea\b', 'férrea'),
    (r'fsica\b', 'física'),
    (r'pblica\b', 'pública'),
    (r'pblicas\b', 'públicas'),
    (r'mbar\b', 'ámbar'),
    (r'rea\b', 'área'),
    (r'reas\b', 'áreas'),
    (r'mnibus\b', 'ómnibus'),
    (r'valo\b', 'óvalo'),
    (r'nico\b', 'único'),
    (r'nica\b', 'única'),
    (r'nicamente\b', 'únicamente'),
    (r'Únicamente\b', 'Únicamente'),
    (r'antigedad\b', 'antigüedad'),
    (r'demarcacin\b', 'demarcación'),
    (r'reduccin\b', 'reducción'),
    (r'Reduccin\b', 'Reducción'),
    (r'aproximacin\b', 'aproximación'),
    (r'ubicacin\b', 'ubicación'),
    (r'Ubicacin\b', 'Ubicación'),
    (r'semforo\b', 'semáforo'),
    (r'semforos\b', 'semáforos'),
    (r'polica\b', 'policía'),
    (r'Polica\b', 'Policía'),
    (r'llantera\b', 'llantería'),
    (r'ferretera\b', 'ferretería'),
    (r'guan\b', 'guían'),
    (r'contina\b', 'continúa'),
    (r'automviles\b', 'automóviles'),
    (r'cdigo\b', 'código'),
    (r'Cdigo\b', 'Código'),
    (r'S\b', 'Sí'),
    (r's\b', 'sí'),
    (r'prohbe\b', 'prohíbe'),
    (r'Prohbe\b', 'Prohíbe'),
    (r'prohibicin\b', 'prohibición'),
    (r'autoriza\b', 'autoriza'),
    (r'estacionar\b', 'estacionar'),
    (r'rpidamente\b', 'rápidamente'),
    (r'rpido\b', 'rápido'),
    (r'alucingenos\b', 'alucinógenos'),
    (r'narcticos\b', 'narcóticos'),
    (r'alcoholmetro\b', 'alcoholímetro'),
    (r'cinturn\b', 'cinturón'),
    (r'badn\b', 'badén'),
    (r'carril\b', 'carril'),
    (r'inmovilizado\b', 'inmovilizado'),
    (r'detencin\b', 'detención'),
    (r'educacin\b', 'educación'),
    (r'escolar\b', 'escolar'),
    (r'informacin\b', 'información'),
    (r'aduanas\b', 'aduanas'),
    (r'delegacin\b', 'delegación'),
    (r'reincidencia\b', 'reincidencia'),
    (r'excepcin\b', 'excepción'),
    (r'excepciones\b', 'excepciones'),
    (r'compaa\b', 'compañía'),
    (r'Compaa\b', 'Compañía'),
    (r'agrcola\b', 'agrícola'),
    (r'estn\b', 'están'),
    (r'ao\b', 'año'),
    (r'aos\b', 'años'),
    (r'nios\b', 'niños'),
    (r'nio\b', 'niño'),
    (r'¿prohibido voltear a la izquierda¿', '"prohibido voltear a la izquierda"'),
    (r'¿CEDA EL PASO\?', '"CEDA EL PASO"'),
    (r'¿U¿', '"U"'),
    (r'¿', '¿'),
    (r'', '')
]

json_path = r'C:\Users\RONALD\Documents\Personal\src\core\training-quiz\server\data\balotario-200.json'
with open(json_path, 'r', encoding='utf-8') as f:
    text = f.read()

for pat, repl in replacements:
    text = re.sub(pat, repl, text)

# Write back
with open(json_path, 'w', encoding='utf-8') as f:
    f.write(text)

# Also write to public/data/balotario-200.json for direct client access
import os
os.makedirs(r'C:\Users\RONALD\Documents\Personal\public\data', exist_ok=True)
with open(r'C:\Users\RONALD\Documents\Personal\public\data\balotario-200.json', 'w', encoding='utf-8') as f:
    f.write(text)

# Check remaining  characters
with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

count_bad = 0
for q in data:
    s = json.dumps(q, ensure_ascii=False)
    if '' in s:
        count_bad += 1
        print(f"Remaining bad in Q{q['id']}: {s}")

print(f"\nAll accents fixed! Remaining questions with replacement char: {count_bad}")
print(f"Total valid questions: {len(data)}")
