import json
import re

json_path = r'C:\Users\RONALD\Documents\Personal\src\core\training-quiz\server\data\balotario-200.json'
with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Direct substring replacements mapping strings with \ufffd
char_replacements = [
    # Question starts
    ('\ufffdQu\ufffd', '¿Qué'),
    ('\ufffdQu', '¿Qué'),
    ('\ufffdqu\ufffd', '¿qué'),
    ('\ufffdC\ufffdndo', '¿Cuándo'),
    ('\ufffdCu\ufffdndo', '¿Cuándo'),
    ('\ufffdC\ufffdal', '¿Cuál'),
    ('\ufffdCu\ufffdal', '¿Cuál'),
    ('\ufffdSe', '¿Se'),
    ('\ufffdSi', '¿Si'),
    ('\ufffdInfluye', '¿Influye'),
    ('\ufffdLa', '¿La'),
    ('\ufffdConstituye', '¿Constituye'),
    ('\ufffdPuede', '¿Puede'),
    ('\ufffdprohibido voltear a la izquierda\ufffd', '"prohibido voltear a la izquierda"'),
    ('\ufffdCEDA EL PASO\ufffd', '"CEDA EL PASO"'),
    ('\ufffdPARE\ufffd', '"PARE"'),
    ('\ufffdU\ufffd', '"U"'),
    
    # Common words
    ('Est\ufffd', 'Está'),
    ('est\ufffd', 'está'),
    ('est\ufffdn', 'están'),
    ('Est\ufffdn', 'Están'),
    ('v\ufffda', 'vía'),
    ('V\ufffda', 'Vía'),
    ('v\ufffdas', 'vías'),
    ('V\ufffdas', 'Vías'),
    ('se\ufffdal', 'señal'),
    ('Se\ufffdal', 'Señal'),
    ('se\ufffdales', 'señales'),
    ('Se\ufffdales', 'Señales'),
    ('se\ufffal', 'señal'),
    ('se\ufffalización', 'señalización'),
    ('se\ufffalética', 'señalética'),
    ('se\ufffalar', 'señalizar'),
    ('se\ufffalados', 'señalados'),
    ('se\ufffale', 'señale'),
    ('gr\ufffdfico', 'gráfico'),
    ('Gr\ufffdfico', 'Gráfico'),
    ('gr\ufffdficos', 'gráficos'),
    ('veh\ufffdculo', 'vehículo'),
    ('Veh\ufffdculo', 'Vehículo'),
    ('veh\ufffdculos', 'vehículos'),
    ('Veh\ufffdculos', 'Vehículos'),
    ('Tr\ufffdnsito', 'Tránsito'),
    ('tr\ufffdnsito', 'tránsito'),
    ('infracci\ufffdn', 'infracción'),
    ('Infracci\ufffdn', 'Infracción'),
    ('infracciones', 'infracciones'),
    ('sanci\ufffdn', 'sanción'),
    ('sancci\ufffdn', 'sanción'),
    ('evaluaci\ufffdn', 'evaluación'),
    ('Evaluaci\ufffdn', 'Evaluación'),
    ('categor\ufffda', 'categoría'),
    ('Categor\ufffda', 'Categoría'),
    ('m\ufffds', 'más'),
    ('M\ufffds', 'Más'),
    ('m\ufffdxima', 'máxima'),
    ('m\ufffdximas', 'máximas'),
    ('m\ufffdximo', 'máximo'),
    ('m\ufffdximos', 'máximos'),
    ('m\ufffdnima', 'mínima'),
    ('m\ufffdnimas', 'mínimas'),
    ('m\ufffdnimo', 'mínimo'),
    ('m\ufffdnimos', 'mínimos'),
    ('podr\ufffdn', 'podrán'),
    ('podr\ufffd', 'podrá'),
    ('detenci\ufffdn', 'detención'),
    ('Detenci\ufffdn', 'Detención'),
    ('prevenci\ufffdn', 'prevención'),
    ('Prevenci\ufffdn', 'Prevención'),
    ('disminuci\ufffdn', 'disminución'),
    ('Disminuci\ufffdn', 'Disminución'),
    ('circulaci\ufffdn', 'circulación'),
    ('Circulaci\ufffdn', 'Circulación'),
    ('direcci\ufffdn', 'dirección'),
    ('posici\ufffdn', 'posición'),
    ('Posici\ufffdn', 'Posición'),
    ('peat\ufffdn', 'peatón'),
    ('Peat\ufffdn', 'Peatón'),
    ('reglamentaci\ufffdn', 'reglamentación'),
    ('obligaci\ufffdn', 'obligación'),
    ('Obligaci\ufffdn', 'Obligación'),
    ('autorizaci\ufffdn', 'autorización'),
    ('revalidaci\ufffdn', 'revalidación'),
    ('recategorizaci\ufffdn', 'recategorización'),
    ('restricci\ufffdn', 'restricción'),
    ('intersecci\ufffdn', 'intersección'),
    ('Intersecci\ufffdn', 'Intersección'),
    ('situaci\ufffdn', 'situación'),
    ('condici\ufffdn', 'condición'),
    ('conducci\ufffdn', 'conducción'),
    ('Conducci\ufffdn', 'Conducción'),
    ('atenci\ufffdn', 'atención'),
    ('comisi\ufffdn', 'comisión'),
    ('inspecci\ufffdn', 'inspección'),
    ('Inspecci\ufffdn', 'Inspección'),
    ('tambi\ufffdn', 'también'),
    ('despu\ufffds', 'después'),
    ('Despu\ufffds', 'Después'),
    ('ser\ufffd', 'será'),
    ('deber\ufffd', 'deberá'),
    ('Deber\ufffd', 'Deberá'),
    ('deber\ufffdn', 'deberán'),
    ('Deber\ufffdn', 'Deberán'),
    ('habr\ufffd', 'habrá'),
    ('efect\ufffda', 'efectúa'),
    ('l\ufffdnea', 'línea'),
    ('L\ufffdnea', 'Línea'),
    ('l\ufffdneas', 'líneas'),
    ('l\ufffdmite', 'límite'),
    ('L\ufffdmite', 'Límite'),
    ('l\ufffdmites', 'límites'),
    ('f\ufffdrreas', 'férreas'),
    ('f\ufffdrrea', 'férrea'),
    ('f\ufffdsica', 'física'),
    ('p\ufffdblica', 'pública'),
    ('p\ufffdblicas', 'públicas'),
    ('\ufffdmbar', 'ámbar'),
    ('\ufffdrea', 'área'),
    ('\ufffdreas', 'áreas'),
    ('\ufffdmnibus', 'ómnibus'),
    ('\ufffdvalo', 'óvalo'),
    ('\ufffdnico', 'único'),
    ('\ufffdnica', 'única'),
    ('\ufffdnicamente', 'únicamente'),
    ('\ufffdnicamente', 'Únicamente'),
    ('antig\ufffdedad', 'antigüedad'),
    ('demarcaci\ufffdn', 'demarcación'),
    ('reducci\ufffdn', 'reducción'),
    ('Reducci\ufffdn', 'Reducción'),
    ('aproximaci\ufffdn', 'aproximación'),
    ('ubicaci\ufffdn', 'ubicación'),
    ('Ubicaci\ufffdn', 'Ubicación'),
    ('sem\ufffdforo', 'semáforo'),
    ('sem\ufffdforos', 'semáforos'),
    ('polic\ufffda', 'policía'),
    ('Polic\ufffda', 'Policía'),
    ('llanter\ufffda', 'llantería'),
    ('ferreter\ufffda', 'ferretería'),
    ('gu\ufffdan', 'guían'),
    ('contin\ufffda', 'continúa'),
    ('autom\ufffdviles', 'automóviles'),
    ('c\ufffddigo', 'código'),
    ('C\ufffddigo', 'Código'),
    ('S\ufffd', 'Sí'),
    ('s\ufffd', 'sí'),
    ('proh\ufffdbe', 'prohíbe'),
    ('Proh\ufffdbe', 'Prohíbe'),
    ('prohibici\ufffdn', 'prohibición'),
    ('r\ufffdpidamente', 'rápidamente'),
    ('r\ufffdpido', 'rápido'),
    ('alucin\ufffdgenos', 'alucinógenos'),
    ('narc\ufffdticos', 'narcóticos'),
    ('alcohol\ufffdmetro', 'alcoholímetro'),
    ('cintur\ufffdn', 'cinturón'),
    ('bad\ufffdn', 'badén'),
    ('informaci\ufffdn', 'información'),
    ('excepci\ufffdn', 'excepción'),
    ('compa\ufffd\ufffda', 'compañía'),
    ('Compa\ufffd\ufffda', 'Compañía'),
    ('compa\ufffda', 'compañía'),
    ('Compa\ufffda', 'Compañía'),
    ('agr\ufffdcola', 'agrícola'),
    ('a\ufffdo', 'año'),
    ('a\ufffdos', 'años'),
    ('ni\ufffdos', 'niños'),
    ('ni\ufffdo', 'niño'),
    ('est\ufffd', 'está'),
    ('Est\ufffd', 'Está'),
    ('luces\ufffd', 'luces'),
    ('\ufffd', '')
]

def clean_value(s):
    if not isinstance(s, str):
        return s
    for target, repl in char_replacements:
        s = s.replace(target, repl)
    return s

for q in data:
    q['prompt'] = clean_value(q['prompt'])
    q['category'] = clean_value(q['category'])
    if q['code']:
        q['code'] = clean_value(q['code'])
    for opt in q['options']:
        opt['text'] = clean_value(opt['text'])

with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

with open(r'C:\Users\RONALD\Documents\Personal\public\data\balotario-200.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Finished fixing all accents!")
